name: Docker Layer Caching
description: Cache images created between main run and post run
branding:
  icon: layers
  color: blue
inputs:
  key:
    description: An explicit key for restoring and saving the cache
    required: true
    default: 'docker-layer-caching-${{ github.workflow }}-{hash}'
  restore-keys:
    description: >-
      An ordered list of keys to use for restoring the cache if no cache hit
      occurred for key
    required: false
    default: 'docker-layer-caching-${{ github.workflow }}-'
runs:
  using: node12
  main: dist/ttsc-dist/main.js/index.js
  post: dist/ttsc-dist/post.js/index.js
